const APP={name:'Bubur Ayam Bandung Akang Hamzah',db:'akang_hamzah_db_v1',version:1};
const DEFAULTS={
 categories:[
  {id:'produk',name:'Menu Bubur',type:'sale',items:[['Bubur Ori',7000],['Bubur Cakwe',12000],['Bubur Telur',12000],['Bubur Ayam Suwir',15000],['Bubur Abon',17000],['Bubur Spesial',13000],['Bubur Istimewa',17000]]},
  {id:'extra',name:'Extra Topping',type:'sale',items:[['Cakwe',2000],['Ayam Suwir',3000],['Abon',5000],['Irisan Telur Dadar',1000],['Telur Rebus',1000],['Kuah',500],['Krupuk',500]]},
  {id:'minuman',name:'Minuman / Lainnya',type:'sale',items:[['Puyuh',3000],['Cleo',1000],['Teh Anget',3000],['Es Teh',3000]]},
  {id:'stok',name:'Stok Perlengkapan',type:'stock',items:[['Paper Bowl',0],['Tali Segel',0],['Sendok',0],['Krupuk',0],['Kripik Pangsit',0],['Bawang Goreng',0],['Kacang Kedelai',0]]},
  {id:'kurang',name:'Kekurangan / Catatan Barang',type:'check',items:[['Cleo',0],['Tisu',0],['Plastik Kecap',0],['Plastik Kuah',0],['Plastik Sambal',0],['Kecap Asin',0],['Kecap Manis',0],['Lada',0],['Kresek Kecil',0],['Kresek Tanggung',0],['Kresek Besar',0]]}
 ],
 wa:'', theme:'navy'
};
let dbPromise;
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(APP.db,APP.version);r.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'});if(!db.objectStoreNames.contains('reports'))db.createObjectStore('reports',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
async function tx(store,mode,fn){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(store,mode);const s=t.objectStore(store);let out;try{out=fn(s)}catch(e){reject(e)}t.oncomplete=()=>resolve(out);t.onerror=()=>reject(t.error)})}
async function getSetting(key){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('settings').objectStore('settings').get(key);r.onsuccess=()=>res(r.result?.value);r.onerror=()=>rej(r.error)})}
async function setSetting(key,value){return tx('settings','readwrite',s=>s.put({key,value,updatedAt:new Date().toISOString()}))}
async function getConfig(){let c=await getSetting('config');if(!c){c=structuredClone(DEFAULTS);await setSetting('config',c)}return c}
async function saveReport(data){return tx('reports','readwrite',s=>s.put(data))}
async function getReportByDate(date){const all=await getAllReports();return all.find(x=>x.tanggal===date)}
async function getAllReports(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction('reports').objectStore('reports').getAll();r.onsuccess=()=>res((r.result||[]).sort((a,b)=>b.tanggal.localeCompare(a.tanggal)));r.onerror=()=>rej(r.error)})}
async function deleteReport(id){return tx('reports','readwrite',s=>s.delete(id))}
const rp=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const today=()=>new Date().toISOString().slice(0,10);
function nav(active){const pages=[['Input1.html','Input 1'],['Input2.html','Input 2'],['Input3.html','Input 3'],['Input4.html','Input 4'],['Input5.html','Input 5'],['laporan1.html','Laporan 1'],['laporan2.html','Laporan 2'],['laporan3.html','Laporan 3'],['laporan4.html','Laporan 4'],['laporan5.html','Laporan 5'],['setting1.html','Setting 1'],['setting2.html','Setting 2'],['setting3.html','Setting 3'],['setting4.html','Setting 4'],['setting5.html','Setting 5']];return `<div class="topnav">${pages.map(p=>`<a class="${active===p[0]?'on':''}" href="${p[0]}">${p[1]}</a>`).join('')}</div>`}
function header(title,sub=''){return `<header class="hero"><div><b class="brand">${APP.name}</b><h1>${title}</h1><p>${sub}</p></div></header>`}
function baseInit(){document.body.insertAdjacentHTML('afterbegin',nav(location.pathname.split('/').pop()||'Input1.html'));}
function num(v){return Number(v||0)}
async function initInput(v){baseInit();const cfg=await getConfig();document.querySelector('#app').innerHTML=header('Input Laporan '+v,'Semua data tersimpan offline di IndexedDB')+`<main class="wrap v${v}"><section class="panel glass"><div class="grid2"><label>Tanggal<input type="date" id="tanggal" value="${today()}"></label><label>Shift / Petugas<input id="petugas" placeholder="Opsional"></label></div><label>Catatan<textarea id="catatan" placeholder="Catatan setor, stok, kekurangan..."></textarea></label></section><section id="forms"></section><section class="stickyTotal"><div><span>Total</span><b id="grand">Rp 0</b></div><button onclick="submitReport()">Simpan</button><button class="ghost" onclick="sendWA()">Kirim WA</button></section></main>`;renderInputForms(cfg,v);window.currentCfg=cfg;document.querySelector('#tanggal').addEventListener('change',loadForDate);await loadForDate();calcAll()}
function renderInputForms(cfg,v){const box=document.querySelector('#forms');box.innerHTML='';cfg.categories.forEach(cat=>{let html=`<section class="panel cat ${cat.type}"><div class="catHead"><h2>${cat.name}</h2><span>${cat.type==='sale'?'jumlah jual':cat.type==='stock'?'stok awal - sisa':'centang kurang'}</span></div>`;if(cat.type==='sale'){html+=`<div class="items ${v==2?'cards':v==3?'compact':v==4?'bigbuttons':'tablelike'}">`+cat.items.map((it,i)=>`<div class="row"><div><b>${it[0]}</b><small>${rp(it[1])}</small></div><div class="qty"><button type="button" onclick="step('${cat.id}_${i}',-1)">−</button><input id="${cat.id}_${i}" data-cat="${cat.id}" data-i="${i}" data-price="${it[1]}" data-name="${it[0]}" type="number" min="0" value="0" oninput="calcAll()"><button type="button" onclick="step('${cat.id}_${i}',1)">+</button></div><strong id="t_${cat.id}_${i}">Rp 0</strong></div>`).join('')+`</div>`}
else if(cat.type==='stock'){html+=`<div class="items compact">`+cat.items.map((it,i)=>`<div class="row"><b>${it[0]}</b><input placeholder="Awal" id="${cat.id}_awal_${i}" type="number" oninput="calcAll()"><input placeholder="Sisa" id="${cat.id}_sisa_${i}" type="number" oninput="calcAll()"><strong id="${cat.id}_laku_${i}">0</strong></div>`).join('')+`</div>`}
else{html+=`<div class="checks">`+cat.items.map((it,i)=>`<label><input type="checkbox" id="${cat.id}_${i}"> ${it[0]}</label>`).join('')+`</div>`}html+='</section>';box.insertAdjacentHTML('beforeend',html)})}
function step(id,d){const el=document.getElementById(id);el.value=Math.max(0,num(el.value)+d);calcAll()}
function calcAll(){let total=0;document.querySelectorAll('input[data-price]').forEach(el=>{const sub=num(el.value)*num(el.dataset.price);total+=sub;const t=document.getElementById('t_'+el.id);if(t)t.textContent=rp(sub)});document.querySelectorAll('[id^="stok_awal_"]').forEach((el,i)=>{const s=document.getElementById('stok_sisa_'+i);const l=document.getElementById('stok_laku_'+i); if(s&&l)l.textContent=num(el.value)-num(s.value)});const g=document.getElementById('grand');if(g)g.textContent=rp(total);return total}
function collectReport(){const cfg=window.currentCfg;const tanggal=document.querySelector('#tanggal').value;const data={id:tanggal,tanggal,petugas:document.querySelector('#petugas').value,catatan:document.querySelector('#catatan').value,total:calcAll(),createdAt:new Date().toISOString(),categories:[]};cfg.categories.forEach(cat=>{const c={id:cat.id,name:cat.name,type:cat.type,items:[]};cat.items.forEach((it,i)=>{if(cat.type==='sale'){const qty=num(document.getElementById(`${cat.id}_${i}`).value);c.items.push({nama:it[0],harga:it[1],jumlah:qty,total:qty*it[1]})}else if(cat.type==='stock'){const awal=num(document.getElementById(`${cat.id}_awal_${i}`).value),sisa=num(document.getElementById(`${cat.id}_sisa_${i}`).value);c.items.push({nama:it[0],awal,sisa,laku:awal-sisa})}else{c.items.push({nama:it[0],kurang:document.getElementById(`${cat.id}_${i}`).checked})}});data.categories.push(c)});return data}
async function submitReport(){await saveReport(collectReport());alert('Laporan tersimpan di IndexedDB')}
async function loadForDate(){const d=document.querySelector('#tanggal').value;const r=await getReportByDate(d);document.querySelector('#petugas').value=r?.petugas||'';document.querySelector('#catatan').value=r?.catatan||'';if(!r){document.querySelectorAll('input[type=number]').forEach(x=>x.value=0);document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);calcAll();return}r.categories?.forEach(cat=>cat.items?.forEach((it,i)=>{if(cat.type==='sale'&&document.getElementById(`${cat.id}_${i}`))document.getElementById(`${cat.id}_${i}`).value=it.jumlah||0;if(cat.type==='stock'&&document.getElementById(`${cat.id}_awal_${i}`)){document.getElementById(`${cat.id}_awal_${i}`).value=it.awal||0;document.getElementById(`${cat.id}_sisa_${i}`).value=it.sisa||0}if(cat.type==='check'&&document.getElementById(`${cat.id}_${i}`))document.getElementById(`${cat.id}_${i}`).checked=!!it.kurang}));calcAll()}
function waText(d){let s=`*${APP.name}*\nTanggal: ${d.tanggal}\nTotal: *${rp(d.total)}*\n`;d.categories.forEach(c=>{s+=`\n*${c.name}*\n`;c.items.forEach(i=>{if((i.jumlah||0)>0)s+=`${i.nama} x${i.jumlah} = ${rp(i.total)}\n`;if((i.laku||0)>0)s+=`${i.nama}: awal ${i.awal}, sisa ${i.sisa}, laku ${i.laku}\n`;if(i.kurang)s+=`- ${i.nama}\n`})});if(d.catatan)s+=`\nCatatan: ${d.catatan}`;return s}
function sendWA(){const d=collectReport();window.open('https://wa.me/'+(window.currentCfg.wa||'')+'?text='+encodeURIComponent(waText(d)),'_blank')}
async function initReport(v){baseInit();document.querySelector('#app').innerHTML=header('Laporan '+v,'Harian dan bulanan dari IndexedDB')+`<main class="wrap report v${v}"><section class="panel"><div class="grid3"><label>Dari<input type="date" id="from"></label><label>Sampai<input type="date" id="to"></label><button onclick="renderReports()">Tampilkan</button></div></section><section id="summary" class="dash"></section><section id="list"></section></main>`;document.querySelector('#from').value=today().slice(0,8)+'01';document.querySelector('#to').value=today();renderReports()}
async function renderReports(){const from=document.querySelector('#from').value,to=document.querySelector('#to').value;const all=(await getAllReports()).filter(r=>r.tanggal>=from&&r.tanggal<=to);const total=all.reduce((a,b)=>a+b.total,0);document.querySelector('#summary').innerHTML=`<div><span>Total Bulan/Range</span><b>${rp(total)}</b></div><div><span>Jumlah Hari Input</span><b>${all.length}</b></div><div><span>Rata-rata</span><b>${rp(all.length?total/all.length:0)}</b></div>`;document.querySelector('#list').innerHTML=all.map(r=>`<article class="panel reportCard"><div class="catHead"><h2>${r.tanggal}</h2><b>${rp(r.total)}</b></div>${r.categories.map(c=>`<details ${c.type==='sale'?'open':''}><summary>${c.name}</summary><table><tbody>${c.items.filter(i=>i.jumlah||i.laku||i.kurang).map(i=>`<tr><td>${i.nama}</td><td>${i.jumlah?i.jumlah:i.laku?('laku '+i.laku):'kurang'}</td><td>${i.total?rp(i.total):''}</td></tr>`).join('')||'<tr><td colspan="3">Tidak ada data</td></tr>'}</tbody></table></details>`).join('')}<button class="danger" onclick="del('${r.id}')">Hapus</button></article>`).join('')||'<div class="panel">Belum ada data pada tanggal ini.</div>'}
async function del(id){if(confirm('Hapus laporan ini?')){await deleteReport(id);renderReports()}}
async function initSetting(v){baseInit();const cfg=await getConfig();window.cfg=cfg;document.querySelector('#app').innerHTML=header('Setting '+v,'Edit menu, harga, urutan, nomor WA, dan kategori')+`<main class="wrap setting v${v}"><section class="panel"><label>Nomor WhatsApp tujuan<input id="wa" value="${cfg.wa||''}" placeholder="628xxxx"></label><button onclick="saveSettings()">Simpan Setting</button><button class="ghost" onclick="addCategory()">Tambah Kategori</button></section><section id="setbox"></section></main>`;renderSettings()}
function renderSettings(){const box=document.querySelector('#setbox');box.innerHTML='';cfg.categories.forEach((c,ci)=>box.insertAdjacentHTML('beforeend',`<section class="panel"><div class="catHead"><input value="${c.name}" onchange="cfg.categories[${ci}].name=this.value"><select onchange="cfg.categories[${ci}].type=this.value"><option ${c.type==='sale'?'selected':''} value="sale">Penjualan</option><option ${c.type==='stock'?'selected':''} value="stock">Stok</option><option ${c.type==='check'?'selected':''} value="check">Checklist</option></select></div><div>${c.items.map((it,i)=>`<div class="setrow"><button onclick="moveItem(${ci},${i},-1)">↑</button><button onclick="moveItem(${ci},${i},1)">↓</button><input value="${it[0]}" onchange="cfg.categories[${ci}].items[${i}][0]=this.value"><input type="number" value="${it[1]}" onchange="cfg.categories[${ci}].items[${i}][1]=Number(this.value)"><button class="danger" onclick="cfg.categories[${ci}].items.splice(${i},1);renderSettings()">Hapus</button></div>`).join('')}</div><button onclick="cfg.categories[${ci}].items.push(['Item Baru',0]);renderSettings()">Tambah Item</button></section>`))}
function moveItem(ci,i,d){const arr=cfg.categories[ci].items,j=i+d;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];renderSettings()}
function addCategory(){cfg.categories.push({id:'cat'+Date.now(),name:'Kategori Baru',type:'sale',items:[['Item Baru',0]]});renderSettings()}
async function saveSettings(){cfg.wa=document.querySelector('#wa').value.trim();await setSetting('config',cfg);alert('Setting tersimpan')}
window.initInput=initInput;window.initReport=initReport;window.initSetting=initSetting;
